moira-kotlin-dsl movement to github
yoomoney/moira-kotlin-dsl pull request #1
Opened 2021-09-13 21:42 UTC by karpenkovk

2021-09-14 05:30 UTC, f0y commented
Добавь файл CODEOWNERS

2021-09-14 05:31 UTC, f0y requested changes

2021-09-14 05:31 UTC, f0y commented on CHANGELOG.md
> +* Изменения связанные с переходом на github
Сделай пжл на английском

2021-09-14 05:31 UTC, f0y commented on dependencies.gradle
> +    compile 'org.jetbrains.kotlin:kotlin-stdlib:1.3.50'
почему их раньше здесь не было?

2021-09-14 19:21 UTC, layfe requested changes

2021-09-14 19:21 UTC, layfe commented on dependencies.gradle
> +    compile 'org.jetbrains.kotlin:kotlin-stdlib:1.3.50'
думаю надо сделать apply kotlin plugin
https://github.com/yoomoney/moira-kotlin-client/pull/1#discussion_r708559915

2021-09-14 19:21 UTC, layfe commented on project.gradle
> +        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50'
изменить на apply нашего kotlin плагин

2021-09-14 21:33 UTC, karpenkovk commented
> Добавь файл CODEOWNERS

2021-09-14 21:34 UTC, karpenkovk commented on CHANGELOG.md
> +* Изменения связанные с переходом на github
fixed

2021-09-14 21:35 UTC, karpenkovk commented on dependencies.gradle
> +    compile 'org.jetbrains.kotlin:kotlin-stdlib:1.3.50'
добавил kotlin-plugin, зависимости kotlin-stdlib и kotlin-script-runtime удалил

2021-09-14 21:37 UTC, karpenkovk commented on project.gradle
> +        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50'
fixed

2021-09-15 12:09 UTC, f0y approved these changes

2021-09-15 12:14 UTC, layfe approved these changes

2021-09-15 12:14 UTC, merged